---
- name: Add object groups to each router for vlan 30
  hosts: routers
  gather_facts: true

  tasks:

    - name: Provision the object group
      ios_config:
        lines:
          - description vlan 30 object group
          - "{{ ansible_facts['net_interfaces']['GigabitEthernet0/1.5']['ipv4'][0]['address'] }} /{{ ansible_facts['net_interfaces']['GigabitEthernet0/1.5']['ipv4'][0]['subnet'] }}"
        parents: object-group network vlan-30

...