---
- name: configure sub interfaces on routers
  hosts: routers

  tasks:

    - name: Provision the sub interface on all routers
      ios_config:
        lines:
          - description vlan 30 sub interface
          - encapsulation dot1q 30
        parents: interface GigabitEthernet0/1.5
      
    - name: Add IP address to sub interface for router 1
      ios_config:
        lines:
          - ip address 192.168.3.2 255.255.255.0
        parents: interface GigabitEthernet0/1.5
      when: inventory_hostname == '192.168.1.107'

    - name: Add IP address to sub interface for router 2
      ios_config:
        lines:
          - ip address 192.168.3.2 255.255.255.0
        parents: interface GigabitEthernet0/1.5
      when: inventory_hostname == '192.168.1.108'

    
    - name: Add IP address to sub interface for router 3
      ios_config:
        lines:
          - ip address 192.168.3.3 255.255.255.0
        parents: interface GigabitEthernet0/1.5
      when: inventory_hostname == '192.168.1.109'

    - name: No shut parent interface to bring up sub interface on all routers
      ios_config:
        lines:
          - no shutdown
        parents: interface GigabitEthernet0/1
...

