---
- name: configure sub interfaces on routers
  hosts: router1

  tasks:
    - name: Add the sub interface if it doesnt exist
      cisco.ios.ios_l3_interfaces:
        config:
        - name: GigabitEthernet0/1.5
          ipv4:
          - address: 192.168.3.3/24
        state: replaced
...

