---
- name: configure sub interfaces on routers
  hosts: router1

  tasks:
    - name: Remove any existing configuration
      ios_l3_interfaces:
        config:
        - name: GigabitEthernet0/1.5
          state: absent
      
    - name: Add config to the interface  
      ios_l3_interfaces:
        config:
        - name: GigabitEthernet0/1.5
          ipv4:
          - address: 192.168.3.3/24

